name: Building for RUT 951, 956

on:
  release:
    types: [created, tagged]
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Prepare IPK package
      run: |
        mkdir -p `pwd`/build/etc/init.d
        mkdir -p `pwd`/build/etc/config
        cp -a openwrt/CONTROL `pwd`/build
        cp openwrt/akita.init `pwd`/build/etc/init.d/akita
        cp openwrt/akita.config `pwd`/build/etc/config/akita
        mkdir -p `pwd`/build/etc/akita/scripts.d
        chmod +x `pwd`/build/etc/init.d/akita
        echo "Architecture: mipsel_24kc" >> build/CONTROL/control

    - name: Build project with Teltonika SDK Toolchain (RUT9M_R 951, 956)
      uses: docker://ganehag/teltonika-sdk-toolchain:RUT9M_R_00.07.03.4
      with:
        args: bash -c "export PATH=/opt/toolchain-mipsel_24kc_gcc-8.4.0_musl/bin:$PATH; ./autogen.sh; ./configure --host=mipsel-openwrt-linux-musl --prefix=`pwd`/build/usr && make install-strip"

    - name: "Build IPK package"
      uses: docker://ganehag/teltonika-sdk-toolchain:RUT9M_R_00.07.03.4
      with:
        args: ipk-build build .

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: modbus-akita_*.ipk
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
